/**
 * HealthCenter
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AddInpatientDTO { 
    patientId?: number;
    practitionerId?: number;
    nurseId?: number | null;
    admissionDate?: Date;
    dischargeDate?: Date | null;
    roomNumber?: string | null;
    bedNumber?: string | null;
    reasonForAdmission?: string | null;
}

