/**
 * HealthCenter
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AddPatientDTO { 
    firstName?: string | null;
    lastName?: string | null;
    dateOfBirth?: Date;
    gender?: string | null;
    address?: string | null;
    phoneNumber?: string | null;
    email?: string | null;
    emergencyContact?: string | null;
    emergencyPhoneNumber?: string | null;
}

