/**
 * HealthCenter
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type AppointmentStatusEnum = 'Scheduled' | 'CheckedIn' | 'Completed' | 'Cancelled';

export const AppointmentStatusEnum = {

    Scheduled: 'Scheduled' as AppointmentStatusEnum,

    CheckedIn: 'CheckedIn' as AppointmentStatusEnum,

    Completed: 'Completed' as AppointmentStatusEnum,

    Cancelled: 'Cancelled' as AppointmentStatusEnum
};

