/**
 * HealthCenter
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ChatMessageDTO } from './chatMessageDTO';


export interface ChatMessageDTOListServiceResponse { 
    data?: Array<ChatMessageDTO> | null;
    success?: boolean;
    message?: string | null;
}

