/**
 * HealthCenter
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ChatRoomDTO } from './chatRoomDTO';


export interface ChatRoomDTOServiceResponse { 
    data?: ChatRoomDTO;
    success?: boolean;
    message?: string | null;
}

