/**
 * HealthCenter
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ChatMessageDTO { 
    messageId?: number;
    chatRoomId?: number;
    senderId?: number;
    content?: string | null;
    createdAt?: Date;
}

