/**
 * HealthCenter
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetAppointmentDTO } from './getAppointmentDTO';


export interface GetAppointmentDTOServiceResponse { 
    data?: GetAppointmentDTO;
    success?: boolean;
    message?: string | null;
}

