/**
 * HealthCenter
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetAppointmentDTO } from './getAppointmentDTO';


export interface GetAppointmentDTOListServiceResponse { 
    data?: Array<GetAppointmentDTO> | null;
    success?: boolean;
    message?: string | null;
}

