/**
 * HealthCenter
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetBedDTO } from './getBedDTO';


export interface GetBedDTOListServiceResponse { 
    data?: Array<GetBedDTO> | null;
    success?: boolean;
    message?: string | null;
}

