/**
 * HealthCenter
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GetBedDTO { 
    bedId?: number;
    roomNumber?: string | null;
    bedNumber?: string | null;
    inpatientId?: number | null;
    patientId?: number;
    patientName?: string | null;
    practitionerId?: number;
    practitionerName?: string | null;
    nurseId?: number | null;
    nurseName?: string | null;
}

