/**
 * HealthCenter
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GetImageRecordDTO { 
    imageId?: number;
    patientId?: number;
    patientName?: string | null;
    practitionerId?: number | null;
    practitionerName?: string | null;
    inpatientId?: number | null;
    imageType?: string | null;
    imageDescription?: string | null;
    imagePath?: string | null;
    captureDate?: Date;
    status?: string | null;
}

