/**
 * HealthCenter
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetImageRecordDTO } from './getImageRecordDTO';


export interface GetImageRecordDTOListServiceResponse { 
    data?: Array<GetImageRecordDTO> | null;
    success?: boolean;
    message?: string | null;
}

