/**
 * HealthCenter
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetInpatientDTO } from './getInpatientDTO';


export interface GetInpatientDTOListServiceResponse { 
    data?: Array<GetInpatientDTO> | null;
    success?: boolean;
    message?: string | null;
}

