/**
 * HealthCenter
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetLabTestDTO } from './getLabTestDTO';


export interface GetLabTestDTOListServiceResponse { 
    data?: Array<GetLabTestDTO> | null;
    success?: boolean;
    message?: string | null;
}

