/**
 * HealthCenter
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GetLabTestDTO { 
    labTestId?: number;
    patientId?: number;
    patientName?: string | null;
    practitionerId?: number;
    practitionerName?: string | null;
    testName?: string | null;
    testResult?: string | null;
    testDate?: Date | null;
}

