/**
 * HealthCenter
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetMedicalHistoryDTOPaginatedResponse } from './getMedicalHistoryDTOPaginatedResponse';


export interface GetMedicalHistoryDTOPaginatedResponseServiceResponse { 
    data?: GetMedicalHistoryDTOPaginatedResponse;
    success?: boolean;
    message?: string | null;
}

