/**
 * HealthCenter
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetMedicalHistoryDTO } from './getMedicalHistoryDTO';


export interface GetMedicalHistoryDTOPaginatedResponse { 
    items?: Array<GetMedicalHistoryDTO> | null;
    currentPage: number;
    pageSize: number;
    totalItems: number;
    totalPages: number;
    readonly hasPrevious?: boolean;
    readonly hasNext?: boolean;
}

