/**
 * HealthCenter
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetMedicationDTO } from './getMedicationDTO';


export interface GetMedicationDTOListServiceResponse { 
    data?: Array<GetMedicationDTO> | null;
    success?: boolean;
    message?: string | null;
}

