/**
 * HealthCenter
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GetMedicationDTO { 
    medicationId?: number;
    name?: string | null;
    dosage?: string | null;
    route?: string | null;
    frequency?: string | null;
    sIdeEffects?: string | null;
}

