/**
 * HealthCenter
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetPrescriptionDTO } from './getPrescriptionDTO';


export interface GetPrescriptionDTOListServiceResponse { 
    data?: Array<GetPrescriptionDTO> | null;
    success?: boolean;
    message?: string | null;
}

