/**
 * HealthCenter
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetPractitionerScheduleDTO } from './getPractitionerScheduleDTO';


export interface GetPractitionerScheduleDTOServiceResponse { 
    data?: GetPractitionerScheduleDTO;
    success?: boolean;
    message?: string | null;
}

