/**
 * HealthCenter
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetPatientDTO } from './getPatientDTO';


export interface GetPatientDTOListServiceResponse { 
    data?: Array<GetPatientDTO> | null;
    success?: boolean;
    message?: string | null;
}

