/**
 * HealthCenter
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GetPractitionerAvailabilityDTO { 
    availableId?: number;
    practitionerId?: number;
    practitionerName?: string | null;
    slotDateTime?: Date;
    isAvailable?: boolean;
}

