/**
 * HealthCenter
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetPrescriptionDTO } from './getPrescriptionDTO';


export interface GetPrescriptionDTOServiceResponse { 
    data?: GetPrescriptionDTO;
    success?: boolean;
    message?: string | null;
}

