/**
 * HealthCenter
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetPractitionerAvailabilityDTO } from './getPractitionerAvailabilityDTO';


export interface GetPractitionerAvailabilityDTOListServiceResponse { 
    data?: Array<GetPractitionerAvailabilityDTO> | null;
    success?: boolean;
    message?: string | null;
}

