/**
 * HealthCenter
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetPractitionerDTO } from './getPractitionerDTO';


export interface GetPractitionerDTOListServiceResponse { 
    data?: Array<GetPractitionerDTO> | null;
    success?: boolean;
    message?: string | null;
}

