/**
 * HealthCenter
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetPractitionerAvailabilityDTO } from './getPractitionerAvailabilityDTO';


export interface GetPractitionerAvailabilityDTOServiceResponse { 
    data?: GetPractitionerAvailabilityDTO;
    success?: boolean;
    message?: string | null;
}

