/**
 * HealthCenter
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetVisitRecordDTO } from './getVisitRecordDTO';


export interface GetVisitRecordDTOListServiceResponse { 
    data?: Array<GetVisitRecordDTO> | null;
    success?: boolean;
    message?: string | null;
}

