/**
 * HealthCenter
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GetVisitRecordDTO { 
    visitId?: number;
    patientId?: number;
    patientName?: string | null;
    practitionerId?: number;
    practitionerName?: string | null;
    scheduleId?: number;
    practitionerSignaturePath?: string | null;
    visitDate?: Date;
    diagnosis?: string | null;
    treatment?: string | null;
    notes?: string | null;
}

