/**
 * HealthCenter
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UpdateBedDTO } from './updateBedDTO';


export interface UpdateBedDTOListServiceResponse { 
    data?: Array<UpdateBedDTO> | null;
    success?: boolean;
    message?: string | null;
}

