/**
 * HealthCenter
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type UserRole = 'Nurse' | 'Practitioner' | 'Patient' | 'Admin';

export const UserRole = {

    Nurse: 'Nurse' as UserRole,

    Practitioner: 'Practitioner' as UserRole,

    Patient: 'Patient' as UserRole,

    Admin: 'Admin' as UserRole
};

