/**
 * HealthCenter
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Practitioner } from './practitioner';
import { UserRole } from './userRole';


export interface User { 
    createdAt?: Date;
    createdBy?: number;
    updatedAt?: Date;
    updatedBy?: number;
    userID?: number;
    email: string;
    userName?: string | null;
    role?: UserRole;
    refreshToken?: string | null;
    tokenCreated?: Date;
    tokenExpires?: Date;
    practitionerId?: number | null;
    practitioner?: Practitioner;
    activationCode?: string | null;
    isActivated?: boolean;
    activationCodeExpires?: Date | null;
    passwordResetToken?: string | null;
    passwordResetTokenExpires?: Date | null;
}
export namespace User {
}


