/**
 * HealthCenter
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { User } from './user';


export interface UserLogHistory { 
    createdAt?: Date;
    createdBy?: number;
    updatedAt?: Date;
    updatedBy?: number;
    logId?: number;
    userId: number;
    userName: string;
    ipAddress: string;
    loginTime: Date;
    logoutTime?: Date | null;
    user?: User;
}

