/**
 * HealthCenter
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserRole } from './userRole';


export interface UserCreateDTO { 
    name?: string | null;
    role?: UserRole;
    email: string;
    password: string;
}
export namespace UserCreateDTO {
}


